# Generated by Django 5.1.3 on 2024-11-22 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tile_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(blank=True, max_length=255)),
                ('format', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='LargeImage',
        ),
    ]
